name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    - name: Install pipx
      run: |
        sudo apt update
        sudo apt install pipx
        pipx ensurepath
        sudo pipx ensurepath --global # optional to allow pipx actions with --global argument

    - name: Install Poetry
      run: |
        pipx install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Build package
      run: |
        poetry build

    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
      run: |
        poetry publish --no-interaction --username "__token__" --password "$POETRY_PYPI_TOKEN"